global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: 'node'
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: 'postgresql'
    static_configs:
      - targets: 
          - postgres-exporter:9187
    metrics_path: /metrics
    params:
      exclude: ['wal']
